experiment:
    project: "eval_llada_instruct" # need to be same of this file name
    num_node: 1 # the number of machines you have
    node_index: 0 # no need to change


model: "/ssd/hf_home/hub/models--GSAI-ML--LLaDA-8B-Instruct/snapshots/9275bf8f5a5687507189baf4657e91c51b2be338" # absolute path of your model
model_base: "llada" # set llada for LLaDA and MMaDA

# dataset you want to eval on, you need to download first, you can also modify your own dataset, see instructions in ./data
dataset:
    eval_dataset: "MATH500" #"MBPP""MATH500""GSM8K""AIME2024""GPQA""LiveCodeBench""HumanEval""LiveBench"
    data_type: "math" #"code""math"

execute:
    num_chunk:  # batch size of executing codes in coding eval tasks

rollout:
    num_response_per_task: 2
    temperature: 0.1
    steps: 256 # total steps of unmasking
    max_gen_length: 256
    batch_size: 2
    remasking_strategy: "low_confidence_static" #"low_confidence_static""low_confidence_dynamic"
    target: "confidence" # target to decide which tokens to unmask, eg. confidence, margin_confidence and neg_entropy
    dynamic_threshold: 0.95 # no use for "low_confidence_static"
    block_size: 256
    output_unmasking_history: False
    use_cache: False




